#!/usr/bin/env lua

require("src.util")

local gel = require("src")

local function usage()
  io.stderr:write("usage: " .. arg[0] .. " source\n")
  os.exit(64)
end

if #arg == 0 then
  while true do
    io.stdout:write("> ")
    local line = io.read()

    if line == "" then break end

    prettyprint(gel.interpret(line))
  end
  print("bye!")
elseif #arg == 1 then
  local source_path = arg[1]
  local source_file = io.open(source_path, "r")
  local source = source_file:read("*a")

  prettyprint(gel.interpret(source))
else
  usage()
end
