#!/usr/bin/env lua

require("src.util")

local gel = require("src")
local qol = require("src.qol")

local function usage()
  io.stderr:write("usage: " .. arg[0] .. " source\n")
  os.exit(64)
end

if #arg == 0 then
  while true do
    io.stdout:write("> ")
    local line = io.read()

    if line == "" then break end

    qol.set_source(line)
    local ast = gel.read(line)
    local result = gel.eval(ast)
    prettyprint(result)
  end
  print("bye!")
elseif #arg == 1 then
  local source_path = arg[1]
  local source_file = io.open(source_path, "r")
  local source = source_file:read("*a")

  qol.set_source(source) -- TODO
  local ast = gel.read(source)
  local result = gel.eval(ast)
  prettyprint(result)
else
  usage()
end
